# Generated by Django 4.0.3 on 2022-03-02 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='adcionado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
