# Generated by Django 4.0.3 on 2022-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_adcionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d'),
        ),
    ]
