# Generated by Django 4.0.3 on 2022-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='link_para_ler',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
